name: Compiling-TeX
on:
  push:
    branches:
      - main
      - 03-ieee-article
jobs:
  build:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    steps:

    - name: Set up Git repository
      uses: actions/checkout@v1

    - name: Compile Poster
      uses: xu-cheng/latex-action@v2
      with:
        root_file: main.tex
        working_directory: oxcidocs/poster

    - name: Compile IEEE article
      uses: xu-cheng/latex-action@v2
      with:
        root_file: main.tex
        working_directory: oxcidocs/ieee-article

    - name: Check pdf files
      run: |
        file oxcidocs/poster/main.pdf | grep -q ' PDF '
        file oxcidocs/ieee-article/main.pdf | grep -q ' PDF '

    - name: Upload
      run: |
        # configure git
        git config --global user.name "mxochicale"
        git config --global user.email "perez.xochicale@gmail.com"
        # setup ssh
        mkdir ~/.ssh
        chmod 700 ~/.ssh
        echo "$DEPLOY_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        git config --global core.sshCommand "ssh -i ~/.ssh/id_rsa -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no"
        git clone --depth=1 --branch generated-pdfs git@github.com:free-cortex/framework.git "$GITHUB_WORKSPACE/deploy"
        cp -f oxcidocs/poster/main.pdf "$GITHUB_WORKSPACE/deploy/poster.pdf"
        cp -f oxcidocs/ieee-article/main.pdf "$GITHUB_WORKSPACE/deploy/ieee-article.pdf"
        cd "$GITHUB_WORKSPACE/deploy"
        git add ieee-article.pdf poster.pdf 
        git commit -m "latex-action deploy"
        git push
      env:
        DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
