name: Compiling-TeX-$ADD_NAME_DOC_TYPE
on:
  push:
    branches:
      - no-main
      - $ADD_ISSUENUMER_NAME

jobs:
  build:
    if: "contains(github.event.head_commit.message, 'CI-TEMPLATE')"
    runs-on: ubuntu-latest
    steps:

    - name: Set up Git repository
      uses: actions/checkout@v1

    - name: Compile $ADD_TYPE_OF_DOCUMENT
      uses: xu-cheng/latex-action@v2
      with:
        root_file: main.tex
        working_directory: odocx/thesis

    - name: Check pdf files
      run: |
        file odocx/thesis/main.pdf | grep -q ' PDF '
 
    - name: Upload
      run: |
        # configure git
        git config --global user.name "mxochicale"
        git config --global user.email "perez.xochicale@gmail.com"
        # setup ssh
        mkdir ~/.ssh
        chmod 700 ~/.ssh
        echo "$DEPLOY_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        git config --global core.sshCommand "ssh -i ~/.ssh/id_rsa -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no"
        git clone --depth=1 --branch pdfs git@github.com:$ADD_MAIN_REPO/$ADD_REPO_NAME.git "$GITHUB_WORKSPACE/deploy"
        cp -f odocx/thesis/main.pdf "$GITHUB_WORKSPACE/deploy/$ADD_FILENAME.pdf"
        cd "$GITHUB_WORKSPACE/deploy"
        git add $ADD_FILE_NAME.pdf 
        git commit -m "latex-action deploy"
        git push
      env:
        DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
